# -*- coding: utf-8 -*-
"""Contact List Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6qntLt1CYlNqPAOzL11EPrNPQjaNpRR
"""

import os
CONTACT_LIST = "contacts.txt"
def load_contacts():
    contacts = {}
    if os.path.exists(CONTACT_LIST):
        with open(CONTACT_LIST, "r") as file:
            for line in file:
                name, phone, email = line.strip().split(",")
                contacts[name] = {"phone": phone, "email": email}
    return contacts
def save_contacts(contacts):
    with open(CONTACT_LIST, "w") as file:
        for name, details in contacts.items():
            file.write(f"{name},{details['phone']},{details['email']}\n")
def add_contact(contacts):
    name = input("Enter name: ")
    phone = input("Enter phone: ")
    email = input("Enter email: ")
    if name in contacts:
        print("Contact already exists:(")
    else:
        contacts[name] = {"phone": phone, "email": email}
        print("Contact added successfully:)")
def view_contacts(contacts):
    if not contacts:
        print("No contacts found.")
        return
    print("\n All Contacts")
    for name, details in contacts.items():
        print(f"Name: {name} | Phone: {details['phone']} | Email: {details['email']}")
    print("-----------------------\n")
def search_contact(contacts):
    name = input("Enter name to search: ")
    if name in contacts:
        print(f"Found!\nName: {name}")
        print(f"Phone: {contacts[name]['phone']}")
        print(f"Email: {contacts[name]['email']}")
    else:
        print("Contact not found.")
def update_contact(contacts):
    name = input("Enter name to update: ")
    if name in contacts:
        print("Leave blank to keep old value.")
        phone = input("New phone: ")
        email = input("New email: ")
        if phone:
            contacts[name]["phone"] = phone
        if email:
            contacts[name]["email"] = email
        print("Contact updated!")
    else:
        print("Contact not found.")
def delete_contact(contacts):
    name = input("Enter name to delete: ")
    if name in contacts:
        del contacts[name]
        print("Contact deleted!")
    else:
        print("Contact not found.")
def main():
    contacts = load_contacts()
    while True:
        print("\n CONTACT BOOK ")
        print("1. Add Contact")
        print("2. View All Contacts")
        print("3. Search Contact")
        print("4. Update Contact")
        print("5. Delete Contact")
        print("6. Save & Exit")
        choice = input("Enter your choice: ")
        if choice == "1":
            add_contact(contacts)
        elif choice == "2":
            view_contacts(contacts)
        elif choice == "3":
            search_contact(contacts)
        elif choice == "4":
            update_contact(contacts)
        elif choice == "5":
            delete_contact(contacts)
        elif choice == "6":
            save_contacts(contacts)
            print("Contacts saved.")
            break
        else:
            print("INVALID , PLEASE SELECT FROM THE OPTIONS GIVEN ABOVE!.")
if __name__ == "__main__":
    main()